version: "3"
services:
  leantec-web-vue:
    container_name: leantec-web-vue
    build: .
    image: leantec/leantec-web-vue:0.2.0
    ports:
      - "80:80"
    mem_limit: 1024m
    volumes:
      - "D:/log/frontend:/var/log/nginx"